PipelineSecrets:
  DockerConfig: '{"auths": {"docker-registry.default.svc:5000": {"auth": "c2VydmljZWFjY291bnQ6ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklpSjkuZXlKcGMzTWlPaUpyZFdKbGNtNWxkR1Z6TDNObGNuWnBZMlZoWTJOdmRXNTBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5dVlXMWxjM0JoWTJVaU9pSnFlQ0lzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVmpjbVYwTG01aGJXVWlPaUpxWlc1cmFXNXpMWGd0Y21WbmFYTjBjbmt0ZEc5clpXNHRkM0ptTmpjaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNXVZVzFsSWpvaWFtVnVhMmx1Y3kxNExYSmxaMmx6ZEhKNUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaVlXSm1NV001TVRFdFpXRTNOQzB4TVdVNUxXRm1NVFF0TURBMU1EVTJPR1V4TmpVeklpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbXA0T21wbGJtdHBibk10ZUMxeVpXZHBjM1J5ZVNKOS5DTGh6eW1zV3hRaU9yM1lIdDIyZHJpcDk1ZzRmMlMzbXlsM1A4aHN4MlFtVHMtVVFKdEh1N3pENE9VaUlhV0hQRGdJRHREN0FMN1FRa0lMcVNDSmN3X3dReTI3WG9FRGU2Sk9tY0JMdDdOVWxWeWo5NUFmanhaNmtuTHB1cWYyM2RPVnlIMHc5cFZrRlRtLVNkLUdwWm45UGk4TE1iSnBNUVQtZUhmVWdpNUdORl9mOHFzZ3VDX2ZaMEVRTnlnNk9KdXN6cHRDbFRWM3dIcC1famVIUlh3MElQVzFobmlVYVBaTm9UMTdqbEhSMnpYNXJ0b1BCQUxWOXJQTWRMajRISlZ3UGpuRVFidU1RdW1lWDRQSUxraDIzT0pvWUgyX2Q0cEotYnBwVnlLVDFsLWRRb2xnczUxWEZUcHBucFlQUnhBSVU4Z01SVVM5aUZUX1FBcTFYMnc="}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: pdc.gtk.gtech.com
    exposer: Route
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: docker-registry.default.svc:5000
        TILLER_NAMESPACE: kube-system
prow: {}
